package com.shellinfo.common.code

data class ConfigMaster(

    var operator_type:String ="",
    var operator_name:String ="",
    var station_id:Int =0,
    var line_id:Int = 0,
    var equipment_id:String ="",
    var equipment_group_id:String ="",
    var equipment_group_name: String ="",
    var terminal_id:String ="",
    var activation_code:String ="",
    var acquirer_id:String ="",
    var operator_id:String ="",
    var minimal_balance:String ="",
    var minimum_fare:String ="",
    var penalty_amount:String ="",
    var db_storage_days:String ="",
    var pos_condition_code:String ="",
    var pos_entry_mode:String ="",
    var terminal_verify_url:String ="",
    var offline_sale_trx_url:String ="",
    var client_id:String ="",
    var reader_type:String ="",
    var vendor_name:String ="",
    var authorization_code:String ="",
    var health_update_frequency:String ="",
    var network_down_time:String ="",
    var hashing:String ="",
    var base_url:String ="",
    var sc_ip_address:String ="",
    var ecu_ip_address:String ="",
    var cc_ip_address:String ="",
    var sc_port:String ="",
    var cc_port:String ="",
    var get_fare_api_url:String ="",
    var entry_validation_api_url:String ="",
    var health_api_url:String ="",
    var entry_trx_api_url:String ="",
    var exit_trx_api_url:String ="",
    var ftp_ip_address:String ="",
    var ftp_port:String ="",
    var ftp_user:String ="",
    var ftp_pass:String ="",
    var log_local_file_name:String ="",
    var log_server_file_name:String ="",
    var log_local_file_path:String ="",
    var log_server_file_path:String ="",
    var log_frequency:String ="",
    var ticket_printer_type:String ="",
    var ticket_printer_name:String ="",
    var payment_gateway:String ="",
    var config_version:String =""
)